services:
  - type: web
    name: ciss-phishing-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false

  - type: web
    runtime: static
    name: ciss-phishing-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /download
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://ciss-phishing-backend.onrender.com
